name: UPB Devops 2024 CICD

on:
  push:
    branches: [cicd-docker-ec2, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest 
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/nodejs-app